"""The LeSysBot mark, one character per pixel.

Generated by scripts/gen_logo.py — do not edit by hand. Change the sprite
there and rerun it; see assets/brand/README.md. ``MARK`` is the 16px cut
(terminal banner + favicon); ``MARK_32`` is the bevelled 32px mark.
"""

MARK = (
    ".kkkkkkkkkkkkkk.",
    "kkkkkkkbbkkkkkkk",
    "kkkkkkkbbkkkkkkk",
    "kkkbkkkbbkkkbkkk",
    "kkkbbkkbbkkbbkkk",
    "kkkkbbkbbkbbkkkk",
    "kkkkkbbbbbbkkkkk",
    "kkkkbbbbbbbbkkkk",
    "kkkkbbbbbbbbkkkk",
    "kkkkkbbbbbbkkkkk",
    "kkkkbbkbbkbbkkkk",
    "kkkbbkkbbkkbbkkk",
    "kkkbkkkbbkkkbkkk",
    "kkkkkkkbbkkkkkkk",
    "kkkkkkkbbkkkkkkk",
    ".kkkkkkkkkkkkkk.",
)

MARK_32 = (
    "...eeeeeeeeeeeeeeeeeeeeeeeeee...",
    "..ekkkkkkkkkkkkkkkkkkkkkkkkkke..",
    ".ekkkkkkkkkkkkkkkkkkkkkkkkkkkke.",
    "ekkkkkkkkkkkkkkllkkkkkkkkkkkkkke",
    "ekkkkkkkkkkkkklbblkkkkkkkkkkkkke",
    "ekkkkkkkkkkkkklbbsdkkkkkkkkkkkke",
    "ekkkkkllkkkkkklbbsdkkkkkllkkkkke",
    "ekkkklbbllkkkklbbsdkkkllbblkkkke",
    "ekkkkklbbblkkklbbsdkklbbbsddkkke",
    "ekkkkkklbbblkklbbsdklbbbsddkkkke",
    "ekkkkkkklbbblklbbsdlbbbsddkkkkke",
    "ekkkkkkkklbbblbbbblbbbsddkkkkkke",
    "ekkkkkkkkklbbbbbbbbbbsddkkkkkkke",
    "ekkkkkkkkkklbbbbbbbbsddkkkkkkkke",
    "ekkkkkkklllbbbbbbbbbblllkkkkkkke",
    "ekkkkkllbbbbbbbbbbbbbbbbllkkkkke",
    "ekkkkklsbbbbbbbbbbbbbbbbssdkkkke",
    "ekkkkkkdlssbbbbbbbbbbsssdddkkkke",
    "ekkkkkkkkddlbbbbbbbbsddddkkkkkke",
    "ekkkkkkkkklbbbbbbbbbblkkkkkkkkke",
    "ekkkkkkkklbbbsbbbbsbbblkkkkkkkke",
    "ekkkkkkklbbbsdlbbsdlbbblkkkkkkke",
    "ekkkkkklbbbsddlbbsdklbbblkkkkkke",
    "ekkkkklbbbsddklbbsdkklbbblkkkkke",
    "ekkkklbbssddkklbbsdkkklsbblkkkke",
    "ekkkkklsdddkkklbbsdkkkkdlsddkkke",
    "ekkkkkkddkkkkklbbsdkkkkkkddkkkke",
    "ekkkkkkkkkkkkklbbsdkkkkkkkkkkkke",
    "ekkkkkkkkkkkkkklsddkkkkkkkkkkkke",
    ".ekkkkkkkkkkkkkkddkkkkkkkkkkkke.",
    "..ekkkkkkkkkkkkkkkkkkkkkkkkkke..",
    "...eeeeeeeeeeeeeeeeeeeeeeeeee...",
)

PALETTE = {
    "k": "#0F172A",
    "e": "#1E293B",
    "d": "#155E75",
    "s": "#0891B2",
    "b": "#22D3EE",
    "l": "#67E8F9",
}
